//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XQLiteMgm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeclareUserData
    {
        public string userid { get; set; }
        public string appid { get; set; }
        public string name { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string idkind { get; set; }
        public string country { get; set; }
        public string sales { get; set; }
        public string @internal { get; set; }
        public System.DateTime createdate { get; set; }
        public System.DateTime lastupdate { get; set; }
        public string isdeclare { get; set; }
        public string syscheck { get; set; }
        public string @operator { get; set; }
    }
}
