//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XQLiteMgm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sales()
        {
            this.CustomerDetail = new HashSet<CustomerDetail>();
        }
    
        public short slseq { get; set; }
        public string name { get; set; }
        public string invoiceTitle { get; set; }
        public string invoiceAddress { get; set; }
        public string ssn { get; set; }
        public string president { get; set; }
        public string contact { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string remark { get; set; }
        public System.DateTime crdate { get; set; }
        public short opseq { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerDetail> CustomerDetail { get; set; }
        public virtual Operator Operator { get; set; }
    }
}
